[[section-concepts]]
== Cross-cutting Concepts

Cross-cutting concepts in aspect-oriented software development, are aspects of a program that affect other concerns. When an application has different components some of these may rely in others these cannot be categorized in a existing section either in the design or implementation aspect. These concepts rely too much in other parts to be its own category. In pur application these concepts are:


=== _Domain Model_
//include and explain UML diagram

=== _Domain Concept_
Message
Pod
Client //to do

=== _Communication_
Explain how messaging works between components //to do

=== _User Interface_ 
Our interface in order to be intuitive and easy to use, it has different colors (also prepared for blind-color people), as a first view everything seems to be clean and easy to understand. It also has a good contrast, the chat is familiar and confortable for the person who is using it.
It has internal coherence and a clear hierarchy, is efficiency, giving more priority to the most important things.

=== _Persistency_ 
Persistence refers to the characteristic of state that outlives the process that created it, our proyect relies on the Solid Platform so the persistence is provided by Solid.
