= sole_chat

image:https://travis-ci.org/Arquisoft/sole_chat.svg?branch=master["Build Status", link="https://travis-ci.org/Arquisoft/sole_chat"]
image:https://coveralls.io/repos/github/Arquisoft/sole_chat/badge.svg["Coverage",link="https://coveralls.io/github/Arquisoft/sole_chat"]
image:https://api.codacy.com/project/badge/Grade/fc7dc1da60ee4e9fb67ccff782625794["Codacy code quality", link="https://www.codacy.com/app/jelabra/dechat_en2b?utm_source=github.com&utm_medium=referral&utm_content=Arquisoft/dechat_en2b&utm_campaign=Badge_Grade"]

== Contributors
* Astrid Gamoneda
* Pablo Fernández
* Nuria San Emeterio
* Javier García
* Emilio Cortina
* Ana Junquera


== What is Sole?
We have created an informative website for the project to better explain what Sole Chat offers.
This webpage can be accessed on this link: https://arquisoft.github.io/sole_chat/about_documentation/[website].

== Online application
This application can be either download and deployed on your computer or run directly from your browser the already deployed version.
If you choose the latter, the application can be accessed on this link: https://arquisoft.github.io/sole_chat/[application].

== Compile and run

The project is an Angular application which once downloaded can be run as:

----
 ng serve -o
----

Once executed, the application should be available at: http://localhost:4200

== Testing

The acceptance tests are at:
 https://github.com/Arquisoft/sole_chat/tree/master/e2e[/e2e].

There are also some
 https://cucumber.io/[Cucumber based tests]
 with a simple user story defined at:
 https://github.com/Arquisoft/sole_chat/tree/master/src/test/resources/features[src/test/resources/features].

To run tests execute:

----
ng e2e
----

== Build documentation

The documentation is done in http://asciidoc.org/[AsciiDoc]
using the https://arc42.org/[arc42] templates.
The source documents are located at
 https://github.com/Arquisoft/sole_chat/tree/master/adocs[/adocs].

Using Angular and the
https://asciidoctor.org/[AsciiDoctor plugin] it is possible to generate
the documentation running previously having installed the gulp plugin in angular:

----
gulp
----

== Site documentation

The https://arquisoft.github.io/sole_chat/about_documentation/docs.html[documentation] is available here




